### ISSUE TITLE
Changes in 24w21a

### ISSUE THREAD

**Issue by xtexx** [misode/template-placer#2]
Minecraft 24w21a changed some paths in datapacks and caused generated datapacks not functioning.

I tested that renaming the following paths fixes it:
- `data/structure_placer/functions/` -> `data/structure_placer/function/`
- `data/minecraft/tags/functions/` -> `data/minecraft/tags/function/`

**Comment by misode** [comment]
@xtexChooser @Tisawesomeness @eingruenesbeb This issue has finally been fixed. Sorry for taking so long!
